1.46.0-1ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/network-manager.postinst b/debian/network-manager.postinst
--- a/debian/network-manager.postinst
+++ b/debian/network-manager.postinst
@@ -20,9 +20,11 @@ set -e
 
 case "$1" in
     configure)
-        # Create netdev group. Members of group netdev get access to the PolicyKit action
-        # org.freedesktop.NetworkManager.settings.modify.system without prior authentication
-        addgroup --quiet --system netdev
+        update-rc.d -f NetworkManager remove >/dev/null
+
+        if [ -x "/etc/init.d/dbus" ]; then
+            invoke-rc.d dbus force-reload || true
+        fi
 
         # This directory can contain sensitive data and should not be world-readable
         chmod 0700 /var/lib/NetworkManager
@@ -57,3 +59,41 @@ esac
 
 #DEBHELPER#
 
+# Run "Netplan Everywhere" migration after debhelper (re-)started
+# NetworkManager.service for us. On every package upgrade.
+DIR="/etc/NetworkManager/system-connections"
+if [ "$1" = "configure" ] && [ -d "$DIR" ]; then
+    mkdir -p /run/netplan/nm-migrate
+    for CON in /etc/NetworkManager/system-connections/*; do
+        TYPE=$(file -bi "$CON" | cut -s -d ";" -f 1)
+        [ "$TYPE" = "text/plain" ] || continue # skip non-keyfiles
+        UUID=$(grep "^uuid=" "$CON" | cut -c 6-)
+        if [ -n "$UUID" ]
+        then
+            # Wait for NetworkManager startup to complete,
+            # so we can safely use nmcli. Wait in every interation to handle
+            # a crashed NetworkManager in the previous migraiton step.
+            if ! nm-online -qs; then
+                echo "SKIP: NetworkManager is not ready ..." 1>&2
+                continue
+            fi
+            BACKUP="/run/netplan/nm-migrate/"$(basename "$CON")
+            ORIG_NAME=$(nmcli --get-values connection.id con show "$UUID") || \
+                { echo "SKIP: $(basename "$CON") ($UUID) unknown to NetworkManager." 1>&2 && \
+                  continue; }
+            cp "$CON" "$BACKUP"
+            echo "Migrating $ORIG_NAME ($UUID) to /etc/netplan" 1>&2
+            # Touch the connection's ID (con-name) to trigger its migration.
+            # The Netplan integration will translate the original NM keyfile from
+            # /etc/NetworkManager/system-connections/* to a YAML file located in
+            # /etc/netplan/90-NM-*.yaml and re-generate a corresponding keyfile in
+            # /run/NetworkManager/system-connections/netplan-NM-*.nmconnection
+            nmcli con mod "$UUID" con-name "$ORIG_NAME" || \
+                (echo "FAILED. Restoring backup ..." 1>&2 && mv "$BACKUP" "$CON" && \
+                 rm -f "/etc/netplan/90-NM-$UUID"*.yaml)
+            rm -f "$BACKUP" # clear backup (if it still exists)
+       fi
+    done
+    rm -rf /run/netplan/nm-migrate # cleanup after ourselves
+    (nm-online -qs && nmcli con reload) || echo "WARNING: NetworkManager could not reload connections ..." 1>&2
+fi
